In [1]:
import numpy as np

import tensorflow as tf

In [2]:
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [19]:
x_data = np.array([[h]], dtype=np.float32) #(batch_size, sequence length, input dimension)

hidden_size = 2
rnn = tf.keras.layers.SimpleRNN(units=hidden_size, return_sequences=True, return_state=True)

outputs, states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
outputs: [[[0.49774322 0.6420193 ]]], shape: (1, 1, 2)
states: [[0.49774322 0.6420193 ]], shape: (1, 2)


In [20]:
x_data = np.array([[h, e, l, l, o]], dtype=np.float32)

hidden_size = 2
rnn = tf.keras.layers.SimpleRNN(units=hidden_size, return_sequences=True, return_state=True)

outputs, states = rnn(x_data)

print('x_data: {}, shape: {} \n'.format(x_data, x_data.shape))
print('outputs: {}, shape: {} \n'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape: (1, 5, 4) 

outputs: [[[ 0.34121484  0.04105452]
  [-0.53974617  0.24268186]
  [ 0.24104525  0.17630343]
  [ 0.24466586 -0.5409046 ]
  [-0.46444875  0.4172612 ]]], shape: (1, 5, 2) 

states: [[-0.46444875  0.4172612 ]], shape: (1, 2)


In [21]:
x_data = np.array([[h, e, l, l, o],
                   [e, o, l, l, l],
                   [l, l, e, e, l]], dtype=np.float32)

hidden_size = 2
rnn = tf.keras.layers.SimpleRNN(units=hidden_size, return_sequences=True, return_state=True)    
outputs, states = rnn(x_data)

print('x_data: {}, shape: {} \n'.format(x_data, x_data.shape))
print('outputs: {}, shape: {} \n'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]], shape: (3, 5, 4) 

outputs: [[[-0.6616912   0.53088856]
  [ 0.9363193   0.23846272]
  [ 0.28962305 -0.8026673 ]
  [ 0.10484887  0.103909  ]
  [-0.67376935  0.67976356]]

 [[ 0.69604975  0.20805915]
  [-0.832511    0.34772292]
  [ 0.93623126 -0.03045019]
  [ 0.12153974 -0.71763796]
  [ 0.28024873  0.14895852]]

 [[ 0.69091624 -0.3029375 ]
  [ 0.128427   -0.4900902 ]
  [ 0.41499394  0.46012697]
  [ 0.6896115  -0.38707992]
  [ 0.07489137 -0.43959436]]], shape: (3, 5, 2) 

states: [[-0.67376935  0.67976356]
 [ 0.28024873  0.14895852]
 [ 0.07489137 -0.43959436]], shape: (3, 2)
