<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#4.-Embedding-layer-Vs.-Pretrained-Embedding" data-toc-modified-id="4.-Embedding-layer-Vs.-Pretrained-Embedding-0.1"><span class="toc-item-num">0.1&nbsp;&nbsp;</span>4. Embedding layer Vs. Pretrained Embedding</a></span><ul class="toc-item"><li><span><a href="#4-1.-Embedding-layer-기초" data-toc-modified-id="4-1.-Embedding-layer-기초-0.1.1"><span class="toc-item-num">0.1.1&nbsp;&nbsp;</span>4-1. Embedding layer 기초</a></span></li><li><span><a href="#4-2.-감성-분류하기(Embedding-layer)" data-toc-modified-id="4-2.-감성-분류하기(Embedding-layer)-0.1.2"><span class="toc-item-num">0.1.2&nbsp;&nbsp;</span>4-2. 감성 분류하기(Embedding layer)</a></span></li><li><span><a href="#4-3.-감성-분류하기(Pre-trained-Embedding)" data-toc-modified-id="4-3.-감성-분류하기(Pre-trained-Embedding)-0.1.3"><span class="toc-item-num">0.1.3&nbsp;&nbsp;</span>4-3. 감성 분류하기(Pre-trained Embedding)</a></span></li></ul></li></ul></li><li><span><a href="#Tensorflow-Hub로부터-Pre-trained-tf.keras.layers-사용하기" data-toc-modified-id="Tensorflow-Hub로부터-Pre-trained-tf.keras.layers-사용하기-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Tensorflow Hub로부터 Pre-trained tf.keras.layers 사용하기</a></span></li></ul></div>

In [1]:
import nltk
from nltk.corpus import stopwords
import gensim
from konlpy.tag import *
# from ckonlpy.tag import Twitter
# import MeCab
from collections import Counter
import tensorflow as tf
import numpy as np
import re
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.datasets import fetch_20newsgroups
import pandas as pd
from math import log
import urllib
import wget
import matplotlib as mpl
import matplotlib.pyplot as plt
import json
import os
import platform
from tqdm.notebook import tqdm
from lxml import etree
import zipfile
from sklearn.datasets import fetch_20newsgroups

plt.style.use("dark_background")

np.set_printoptions(precision=3)

# okt = Okt()
# kkm = Kkma()
# kmr = Komoran()
# hnn = Hannanum()

# class Mecab:
#     def pos(self, text):
#         p = re.compile(".+\t[A-Z]+")
#         return [tuple(p.match(line).group().split("\t")) for line in MeCab.Tagger().parse(text).splitlines()[:-1]]
    
#     def morphs(self, text):
#         p = re.compile(".+\t[A-Z]+")
#         return [p.match(line).group().split("\t")[0] for line in MeCab.Tagger().parse(text).splitlines()[:-1]]
    
#     def nouns(self, text):
#         p = re.compile(".+\t[A-Z]+")
#         temp = [tuple(p.match(line).group().split("\t")) for line in MeCab.Tagger().parse(text).splitlines()[:-1]]
#         nouns=[]
#         for word in temp:
#             if word[1] in ["NNG", "NNP", "NNB", "NNBC", "NP", "NR"]:
#                 nouns.append(word[0])
#         return nouns
    
# mc = Mecab()

nltk.download("punkt")
nltk.download("stopwords")
nltk.download("wordnet")

path = "C:/Windows/Fonts/malgun.ttf"
if platform.system() == "Darwin":
    mpl.rc("font", family="AppleGothic")
elif platform.system() == "Windows":
    font_name = mpl.font_manager.FontProperties(fname=path).get_name()
    mpl.rc('font', family=font_name)
    
mpl.rc("axes", unicode_minus=False)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\82104\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\82104\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\82104\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [ ]:
# !pip install glove_python

In [2]:
import glove

ModuleNotFoundError: No module named 'glove'

In [ ]:
import glove

corpus = Corpus() 
corpus.fit(result, window=5)
# 훈련 데이터로부터 GloVe에서 사용할 동시 등장 행렬 생성

glove = Glove(no_components=100, learning_rate=0.05)
glove.fit(corpus.matrix, epochs=20, no_threads=4, verbose=True)
glove.add_dictionary(corpus.dictionary)
# 학습에 이용할 쓰레드의 개수는 4로 설정, 에포크는 20.

Performing 20 training epochs with 4 threads
Epoch 0
Epoch 1
Epoch 2
Epoch 3
Epoch 4
Epoch 5
Epoch 6
Epoch 7
Epoch 8
Epoch 9
Epoch 10
Epoch 11
Epoch 12
Epoch 13
Epoch 14
Epoch 15
Epoch 16
Epoch 17
Epoch 18
Epoch 19


In [ ]:
model_result1 = glove.most_similar("man")
print(model_result1)

[('woman', 0.9605876132425566), ('guy', 0.8873543995635172), ('girl', 0.851644711353462), ('young', 0.8454644715719105)]


In [ ]:
model_result2=glove.most_similar("boy")
print(model_result2)

[('girl', 0.9419230106533926), ('kid', 0.8353257929535401), ('woman', 0.8300046728060503), ('man', 0.8214572429272888)]


In [ ]:
model_result3=glove.most_similar("university")
print(model_result3)

[('harvard', 0.8891058026544912), ('mit', 0.8655953916957512), ('stanford', 0.8466465957274574), ('cambridge', 0.8443982653416059)]


In [ ]:
model_result4=glove.most_similar("water")
print(model_result4)

[('clean', 0.8497457787246371), ('air', 0.8434838133871023), ('fresh', 0.8294691419399418), ('electricity', 0.8201486509192097)]


In [ ]:
model_result5=glove.most_similar("physics")
print(model_result5)

[('chemistry', 0.8879813137524931), ('economics', 0.8671791836455324), ('biology', 0.851880595257216), ('mathematics', 0.8505414029308055)]


In [ ]:
model_result6=glove.most_similar("muscle")
print(model_result6)

[('tissue', 0.8330768461898297), ('nerve', 0.8261792360472352), ('skeletal', 0.7678621802032819), ('stem', 0.7529100804581816)]


In [ ]:
model_result7=glove.most_similar("clean")
print(model_result7)

[('fresh', 0.8671807133278371), ('water', 0.8497457787246372), ('drinking', 0.7980126180711001), ('heat', 0.7928526111116708)]


## 4. Embedding layer Vs. Pretrained Embedding

### 4-1. Embedding layer 기초

In [ ]:
# 임의의 문서 3개 생성
sample_text_1 = "bitty bought a bit of butter"
sample_text_2 = "but the bit of butter was a bit bitter"
sample_text_3 = "so she bought some better butter to make the bitter butter better"

docs = [sample_text_1, sample_text_2, sample_text_3]
n_docs=len(docs)

In [ ]:
vocab_size = 50
tkn = tf.keras.preprocessing.text.Tokenizer(num_words=vocab_size+1)
tkn.fit_on_texts(docs)

corpus_idx = tkn.texts_to_sequences(docs)

In [ ]:
print(tkn.word_index)
print(corpus_idx)

{'butter': 1, 'bit': 2, 'bought': 3, 'a': 4, 'of': 5, 'the': 6, 'bitter': 7, 'better': 8, 'bitty': 9, 'but': 10, 'was': 11, 'so': 12, 'she': 13, 'some': 14, 'to': 15, 'make': 16}
[[9, 3, 4, 2, 5, 1], [10, 6, 2, 5, 1, 11, 4, 2, 7], [12, 13, 3, 14, 8, 1, 15, 16, 6, 7, 1, 8]]


In [ ]:
# corpus_idx=[]
# for i, doc in enumerate(docs):
#     corpus_idx.append(tf.keras.preprocessing.text.one_hot(doc, 50))

In [ ]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Embedding(input_dim=vocab_size, output_dim=128))

In [ ]:
# 룩업 테이블 저장
emb_matrix = model.layers[0].get_weights()[0]

In [ ]:
# 룩업 테이블 크기 확인
print(emb_matrix.shape)

(50, 128)


In [ ]:
# 34번째 단어 임베딩 값 확인
emb_matrix[34]

array([ 0.03263989, -0.02002963, -0.02926129,  0.04062835,  0.03773863,
        0.02971169,  0.02677151,  0.01759437, -0.01188103, -0.04960748,
       -0.02214905, -0.04100679,  0.02732602, -0.02526584, -0.04764689,
        0.0352012 ,  0.03894139, -0.00759046,  0.00392884, -0.04250013,
       -0.04886044,  0.0075701 , -0.03111113, -0.01642779, -0.01951819,
       -0.04288147, -0.04315158, -0.03305702, -0.04738927, -0.01854967,
        0.01183575, -0.00665712,  0.00902815,  0.03308349,  0.04552216,
        0.04750897,  0.0264256 ,  0.04714967,  0.04600301,  0.04704997,
        0.01090372, -0.02848966,  0.02545423,  0.0307886 , -0.02648999,
       -0.0449039 , -0.01753411, -0.01702175, -0.01818275,  0.0410333 ,
        0.01874287, -0.03222505, -0.03681958, -0.02393687,  0.02087081,
       -0.00901114, -0.01822656, -0.02156426, -0.02489222, -0.0186474 ,
       -0.0010251 , -0.00876205,  0.02386303, -0.04325956, -0.02246397,
       -0.02926103,  0.01149505,  0.01657571, -0.00582244,  0.02

In [ ]:
# 첫번째 문서 임베딩화
emb_matrix[corpus_idx[0]].shape

(6, 128)

### 4-2. 감성 분류하기(Embedding layer)

In [ ]:
sents = ["nice great best amazing", "stop lies", "pitiful nerd", "excellent work", "supreme quality", "bad", "highly respectable"]
y_train = [1, 0, 0, 1, 1, 0, 1]

tkn = tf.keras.preprocessing.text.Tokenizer()
tkn.fit_on_texts(sents)
vocab_size = len(tkn.word_index)

In [ ]:
tkn.word_index

{'nice': 1,
 'great': 2,
 'best': 3,
 'amazing': 4,
 'stop': 5,
 'lies': 6,
 'pitiful': 7,
 'nerd': 8,
 'excellent': 9,
 'work': 10,
 'supreme': 11,
 'quality': 12,
 'bad': 13,
 'highly': 14,
 'respectable': 15}

In [ ]:
corpus_idx = tkn.texts_to_sequences(sents)

In [ ]:
print(corpus_idx)

[[1, 2, 3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13], [14, 15]]


In [ ]:
max_len = max([len(i) for i in corpus_idx])

X_train = tf.keras.preprocessing.sequence.pad_sequences(corpus_idx, maxlen=max_len, padding="post")
y_train = np.array(y_train)

In [ ]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Embedding(input_dim=vocab_size+1, output_dim=4, input_length=max_len))
model.add(tf.keras.layers.Flatten()) # tf.keras.layers.Dense의 입력으로 넣기위함.
model.add(tf.keras.layers.Dense(1, activation="sigmoid"))

In [ ]:
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["binary_accuracy"])

model.fit(X_train, y_train, epochs=100, verbose=2)

Epoch 1/100
1/1 - 0s - loss: 0.6871 - binary_accuracy: 0.5714
Epoch 2/100
1/1 - 0s - loss: 0.6857 - binary_accuracy: 0.5714
Epoch 3/100
1/1 - 0s - loss: 0.6843 - binary_accuracy: 0.5714
Epoch 4/100
1/1 - 0s - loss: 0.6829 - binary_accuracy: 0.5714
Epoch 5/100
1/1 - 0s - loss: 0.6815 - binary_accuracy: 0.5714
Epoch 6/100
1/1 - 0s - loss: 0.6801 - binary_accuracy: 0.5714
Epoch 7/100
1/1 - 0s - loss: 0.6787 - binary_accuracy: 0.5714
Epoch 8/100
1/1 - 0s - loss: 0.6773 - binary_accuracy: 0.5714
Epoch 9/100
1/1 - 0s - loss: 0.6759 - binary_accuracy: 0.5714
Epoch 10/100
1/1 - 0s - loss: 0.6745 - binary_accuracy: 0.5714
Epoch 11/100
1/1 - 0s - loss: 0.6731 - binary_accuracy: 0.5714
Epoch 12/100
1/1 - 0s - loss: 0.6717 - binary_accuracy: 0.5714
Epoch 13/100
1/1 - 0s - loss: 0.6704 - binary_accuracy: 0.5714
Epoch 14/100
1/1 - 0s - loss: 0.6690 - binary_accuracy: 0.5714
Epoch 15/100
1/1 - 0s - loss: 0.6676 - binary_accuracy: 0.5714
Epoch 16/100
1/1 - 0s - loss: 0.6662 - binary_accuracy: 0.5714
E

### 4-3. 감성 분류하기(Pre-trained Embedding)

In [ ]:
path = "GoogleNews-vectors-negative300.bin.gz"
if os.path.exists(path):
    pass
else:
    wget.download(f"https://s3.amazonaws.com/dl4j-distribution/{path}")

# 구글의 사전 훈련된 Word2vec 모델을 로드합니다.
w2v_google = gensim.models.KeyedVectors.load_word2vec_format(path, binary=True)

In [ ]:
print(w2v_google.vectors.shape) # 모델의 크기 확인

(3000000, 300)


In [ ]:
#단어 집합 크기의 행과 300개의 열을 가지는 행렬 생성. 값은 전부 0으로 채워진다.
emb_matrix = np.zeros((vocab_size+1, 300))

In [ ]:
def get_vector(word):
    if word in w2v_google:
        return w2v_google[word]
    else:
        return None

In [ ]:
print(tkn.word_index)

{'nice': 1, 'great': 2, 'best': 3, 'amazing': 4, 'stop': 5, 'lies': 6, 'pitiful': 7, 'nerd': 8, 'excellent': 9, 'work': 10, 'supreme': 11, 'quality': 12, 'bad': 13, 'highly': 14, 'respectable': 15}


In [ ]:
for word, idx in tkn.word_index.items():
    try:
        emb_matrix[idx] = w2v_google[word]
    except:
        continue

In [ ]:
w2v_google["supreme"]

array([ 0.174,  0.173,  0.113,  0.166,  0.059, -0.014,  0.129, -0.218,
        0.074,  0.205, -0.097, -0.011, -0.032,  0.064, -0.054,  0.116,
        0.215,  0.116, -0.108,  0.021,  0.124,  0.079, -0.244,  0.119,
        0.219, -0.142, -0.093,  0.099,  0.132, -0.012,  0.057,  0.124,
        0.118,  0.512,  0.046, -0.021,  0.017,  0.109,  0.117,  0.085,
        0.17 , -0.246,  0.129, -0.045, -0.004, -0.149,  0.237,  0.12 ,
       -0.157, -0.024, -0.047,  0.188,  0.008,  0.307, -0.101,  0.099,
       -0.266, -0.357,  0.059, -0.021,  0.012,  0.06 ,  0.234, -0.018,
        0.002, -0.042,  0.188,  0.025, -0.076, -0.029, -0.021, -0.058,
       -0.047,  0.17 ,  0.046, -0.132,  0.033,  0.018,  0.147, -0.107,
       -0.108,  0.04 ,  0.068, -0.095,  0.157, -0.234, -0.038,  0.053,
       -0.074, -0.021, -0.055, -0.226,  0.033, -0.044,  0.004, -0.041,
       -0.134,  0.046, -0.096, -0.242,  0.165,  0.204,  0.086, -0.086,
       -0.112,  0.224, -0.164, -0.083, -0.034,  0.035,  0.158,  0.134,
      

In [ ]:
emb_matrix[11]

array([ 0.174,  0.173,  0.113,  0.166,  0.059, -0.014,  0.129, -0.218,
        0.074,  0.205, -0.097, -0.011, -0.032,  0.064, -0.054,  0.116,
        0.215,  0.116, -0.108,  0.021,  0.124,  0.079, -0.244,  0.119,
        0.219, -0.142, -0.093,  0.099,  0.132, -0.012,  0.057,  0.124,
        0.118,  0.512,  0.046, -0.021,  0.017,  0.109,  0.117,  0.085,
        0.17 , -0.246,  0.129, -0.045, -0.004, -0.149,  0.237,  0.12 ,
       -0.157, -0.024, -0.047,  0.188,  0.008,  0.307, -0.101,  0.099,
       -0.266, -0.357,  0.059, -0.021,  0.012,  0.06 ,  0.234, -0.018,
        0.002, -0.042,  0.188,  0.025, -0.076, -0.029, -0.021, -0.058,
       -0.047,  0.17 ,  0.046, -0.132,  0.033,  0.018,  0.147, -0.107,
       -0.108,  0.04 ,  0.068, -0.095,  0.157, -0.234, -0.038,  0.053,
       -0.074, -0.021, -0.055, -0.226,  0.033, -0.044,  0.004, -0.041,
       -0.134,  0.046, -0.096, -0.242,  0.165,  0.204,  0.086, -0.086,
       -0.112,  0.224, -0.164, -0.083, -0.034,  0.035,  0.158,  0.134,
      

In [ ]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Embedding(input_dim=vocab_size+1, output_dim=300, weights=[emb_matrix], input_length=max_len, trainable=False))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(1, activation="sigmoid"))

model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["binary_accuracy"])

model.fit(X_train, y_train, epochs=100, verbose=2)

Epoch 1/100
1/1 - 0s - loss: 0.7204 - binary_accuracy: 0.2857
Epoch 2/100
1/1 - 0s - loss: 0.7013 - binary_accuracy: 0.2857
Epoch 3/100
1/1 - 0s - loss: 0.6827 - binary_accuracy: 0.5714
Epoch 4/100
1/1 - 0s - loss: 0.6646 - binary_accuracy: 0.7143
Epoch 5/100
1/1 - 0s - loss: 0.6471 - binary_accuracy: 0.7143
Epoch 6/100
1/1 - 0s - loss: 0.6302 - binary_accuracy: 0.8571
Epoch 7/100
1/1 - 0s - loss: 0.6138 - binary_accuracy: 0.8571
Epoch 8/100
1/1 - 0s - loss: 0.5979 - binary_accuracy: 1.0000
Epoch 9/100
1/1 - 0s - loss: 0.5825 - binary_accuracy: 1.0000
Epoch 10/100
1/1 - 0s - loss: 0.5677 - binary_accuracy: 1.0000
Epoch 11/100
1/1 - 0s - loss: 0.5533 - binary_accuracy: 1.0000
Epoch 12/100
1/1 - 0s - loss: 0.5394 - binary_accuracy: 1.0000
Epoch 13/100
1/1 - 0s - loss: 0.5260 - binary_accuracy: 1.0000
Epoch 14/100
1/1 - 0s - loss: 0.5131 - binary_accuracy: 1.0000
Epoch 15/100
1/1 - 0s - loss: 0.5006 - binary_accuracy: 1.0000
Epoch 16/100
1/1 - 0s - loss: 0.4885 - binary_accuracy: 1.0000
E

# Tensorflow Hub로부터 Pre-trained tf.keras.layers 사용하기

In [ ]:
import tensorflow as tf
import tensorflow_datasets as tfds
import tensorflow_hub as hub

In [ ]:
(train_data, validation_data, test_data), info = tfds.load("imdb_reviews", split=["train[:80%]", "train[80%:90%]", "train[90%:]"], with_info=True, as_supervised=True)

In [ ]:
train_examples_batch, train_labels_batch = next(iter(train_data.batch(10)))
train_examples_batch

<tf.Tensor: shape=(10,), dtype=string, numpy=
array([b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.",
       b'I have been known to fall asleep during films, but this is usually due to a combination of things including, really tired, being warm and comfortable on the sette and having just eaten a lot. However on this occasion I fell 

In [ ]:
train_labels_batch

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0])>

In [ ]:
tf.keras.layers = "https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1"
hub_layer = hub.KerasLayer(tf.keras.layers, input_shape=[], 
                           dtype=tf.string, trainable=True)
hub_layer(train_examples_batch[:3])

<tf.Tensor: shape=(3, 20), dtype=float32, numpy=
array([[ 1.765786  , -3.882232  ,  3.9134233 , -1.5557289 , -3.3362343 ,
        -1.7357955 , -1.9954445 ,  1.2989551 ,  5.081598  , -1.1041286 ,
        -2.0503852 , -0.72675157, -0.65675956,  0.24436149, -3.7208383 ,
         2.0954835 ,  2.2969332 , -2.0689783 , -2.9489717 , -1.1315987 ],
       [ 1.8804485 , -2.5852382 ,  3.4066997 ,  1.0982676 , -4.056685  ,
        -4.891284  , -2.785554  ,  1.3874227 ,  3.8476458 , -0.9256538 ,
        -1.896706  ,  1.2113281 ,  0.11474707,  0.76209456, -4.8791065 ,
         2.906149  ,  4.7087674 , -2.3652055 , -3.5015898 , -1.6390051 ],
       [ 0.71152234, -0.6353217 ,  1.7385626 , -1.1168286 , -0.5451594 ,
        -1.1808156 ,  0.09504455,  1.4653089 ,  0.66059524,  0.79308075,
        -2.2268345 ,  0.07446612, -1.4075904 , -0.70645386, -1.907037  ,
         1.4419787 ,  1.9551861 , -0.42660055, -2.8022065 ,  0.43727064]],
      dtype=float32)>

In [ ]:
model = tf.keras.tf.keras.models()
model.add(hub_layer)
model.add(tf.keras.layers.tf.keras.layers.Dense(16, activation="relu"))
model.add(tf.keras.layers.tf.keras.layers.Dense(1, activation="sigmoid"))

model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
keras_layer (KerasLayer)     (None, 20)                400020    
_________________________________________________________________
dense_2 (Dense)              (None, 16)                336       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 17        
Total params: 400,373
Trainable params: 400,373
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer="adam",
              loss="binary_crossentropy",
              metrics=["accuracy"])

In [ ]:
history = model.fit(train_data.shuffle(10000).batch(512),
                    epochs=20,
                    validation_data=validation_data.batch(512),
                    verbose=1)

Epoch 1/20
40/40 [==============================] - 3s 79ms/step - loss: 1.0590 - accuracy: 0.4897 - val_loss: 0.7653 - val_accuracy: 0.4656
Epoch 2/20
40/40 [==============================] - 3s 69ms/step - loss: 0.7244 - accuracy: 0.5088 - val_loss: 0.6995 - val_accuracy: 0.5448
Epoch 3/20
40/40 [==============================] - 3s 71ms/step - loss: 0.6714 - accuracy: 0.5929 - val_loss: 0.6558 - val_accuracy: 0.6228
Epoch 4/20
40/40 [==============================] - 3s 70ms/step - loss: 0.6317 - accuracy: 0.6512 - val_loss: 0.6214 - val_accuracy: 0.6648
Epoch 5/20
40/40 [==============================] - 3s 68ms/step - loss: 0.5965 - accuracy: 0.6873 - val_loss: 0.5880 - val_accuracy: 0.6968
Epoch 6/20
40/40 [==============================] - 3s 68ms/step - loss: 0.5611 - accuracy: 0.7211 - val_loss: 0.5517 - val_accuracy: 0.7220
Epoch 7/20
40/40 [==============================] - 3s 70ms/step - loss: 0.5224 - accuracy: 0.7526 - val_loss: 0.5142 - val_accuracy: 0.7508
Epoch 8/20
40

In [ ]:
results = model.evaluate(test_data.batch(512), verbose=2)
for name, value in zip(model.metrics_names, results):
    print("%s: %.3f" % (name, value))

NameError: name 'model' is not defined