<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Greedy-Search" data-toc-modified-id="Greedy-Search-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Greedy Search</a></span></li><li><span><a href="#Beam-Search" data-toc-modified-id="Beam-Search-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Beam Search</a></span></li></ul></div>

In [48]:
import math
import numpy as np
import random

In [49]:
probs = [1, 2, 3, 4, 5]
data = np.array([random.sample(probs, k=5) for _ in range(10)])

# Greedy Search

In [50]:
def greedy_search(data):
    return np.argmax(data, axis=1)

In [51]:
greedy_search(data)

array([2, 0, 1, 0, 4, 1, 1, 0, 2, 1], dtype=int64)

# Beam Search

In [52]:
def beam_search(data, k):
    seq_score = [[list(), 0]]
    for probs in data:
        cands = list()
        for seq, score in seq_score:
            for i, prob in enumerate(probs):
                cands.append([seq + [i], score - np.log(prob)])
        seq_score.extend(cands)
        seq_score = sorted(seq_score, key=lambda x:x[1])[:k]
    return [np.array(i[0]) for i in seq_score]

In [54]:
beam_search(data, 4)

[array([2, 0, 1, 0, 4, 1, 1, 0, 2, 1]),
 array([2, 0, 1, 0, 4, 1, 1, 0, 2, 4]),
 array([2, 0, 1, 0, 4, 1, 1, 0, 0, 1]),
 array([2, 0, 1, 0, 4, 1, 1, 1, 2, 1])]